TASK 1 - Creating a simple webpage
Madlabs-Internship/html-fun pull request #2
Opened 2021-04-05 10:15 UTC by Mahesh0334

This is the first task in HTML and CSS. The main aim of this task is to create a
simple good loking Webpage. The most important topic here in this task
is "Containers".

2021-04-05 11:09 UTC, ajomadlabs requested changes
This is a great attempt,

Do improve on 
- Intendation
- Class Namings
- Avoid using br tags
- Avoid using inline styles

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<title> TAskRedo</title>
Can you make this consistent

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +<html>
Before this we have something called `<!DOCTYPE html>`. Can you please check on this topic

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<link rel="stylesheet" href="style.css">
`type` attribute is missing

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +	<head>
`char` and `lang` attribute is missing. Can you check on this

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<div class ="in-a-box">
Pleas have proper naming conventions. Instead of `in-a-box` have it like `box or section or anything meaningful`

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +			<div class="img"> <br>
Naming convention can be improved `image`

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +			<div class="img"> <br>
Why is this `br` being used instead we can directly do this with css

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +				<h1 style="font-family:'Courier New', monospace">M A D L A B S</h1><br>
Please do not use `inline-styles` instead go for `classes`

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<br> <br>
Avoid using `br` tags where ever possible

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<h2 style="font-family:'Courier New'">Heading One</h2>
Avoid using inline styles

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<p style="font-family:verdana">Hi task assigned by AJO JOHN - MadLabs, Hi task assigned by AJO JOHN - MadLabs, Hi task assigned by AJO JOHN - MadLabs, Hi task assigned by AJO JOHN - MadLabs, Hi tas
Avoid using inline styles

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<h2 style="font-family:'Courier New'">Heading Two</h2>
Avoid using inline styles

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/index.html
> +		<p style="font-family:verdana">Hi task completed successfully on monday, Hi task completed successfully on monday, Task completed successfully on monday, Hi task completed successfully on monday, H
Avoid using inline styles

2021-04-05 11:09 UTC, ajomadlabs commented on mahesh/style.css
> +hr {
Please remove this empty style

2021-04-05 12:00 UTC, Mahesh0334 commented on mahesh/index.html
> +		<link rel="stylesheet" href="style.css">
I didn't understand this.

2021-04-06 08:33 UTC, ajomadlabs requested changes

2021-04-06 08:33 UTC, ajomadlabs commented on mahesh/index.html
> +<html>
This should not be `element` it's supposed to be this way
```
<html lang="en">
<head>
<meta charset="UTF-8">
</head>
</html>
```

2021-04-06 09:20 UTC, ajomadlabs approved these changes
LGTM 🎉

2021-04-06 09:20 UTC, merged